# Generated by Django 4.1 on 2022-08-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('cnic', models.IntegerField(max_length=13)),
                ('contact', models.IntegerField(max_length=11)),
                ('city', models.CharField(max_length=70)),
            ],
        ),
    ]
