# Generated by Django 4.1 on 2022-08-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cnic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
